[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
xshell = "0.2"
rlimit = "0.10.2"
risc0-groth16-sys = { workspace = true, optional = true, features = [
  "cuda",
  "setup",
] }

[features]
default = ["setup-groth16"]
setup-groth16 = ["dep:risc0-groth16-sys"]